// src/services/countryService.js
// Provides country names and flags for all countries

const countryData = {
  "AF": { name: "Afghanistan", flag: "🇦🇫" },
  "AL": { name: "Albanien", flag: "🇦🇱" },
  "DZ": { name: "Algerien", flag: "🇩🇿" },
  "AS": { name: "Amerikanisch-Samoa", flag: "🇦🇸" },
  "AD": { name: "Andorra", flag: "🇦🇩" },
  "AO": { name: "Angola", flag: "🇦🇴" },
  "AI": { name: "Anguilla", flag: "🇦🇮" },
  "AQ": { name: "Antarktis", flag: "🇦🇶" },
  "AG": { name: "Antigua und Barbuda", flag: "🇦🇬" },
  "AR": { name: "Argentinien", flag: "🇦🇷" },
  "AM": { name: "Armenien", flag: "🇦🇲" },
  "AW": { name: "Aruba", flag: "🇦🇼" },
  "AU": { name: "Australien", flag: "🇦🇺" },
  "AT": { name: "Österreich", flag: "🇦🇹" },
  "AZ": { name: "Aserbaidschan", flag: "🇦🇿" },
  "BS": { name: "Bahamas", flag: "🇧🇸" },
  "BH": { name: "Bahrain", flag: "🇧🇭" },
  "BD": { name: "Bangladesch", flag: "🇧🇩" },
  "BB": { name: "Barbados", flag: "🇧🇧" },
  "BY": { name: "Belarus", flag: "🇧🇾" },
  "BE": { name: "Belgien", flag: "🇧🇪" },
  "BZ": { name: "Belize", flag: "🇧🇿" },
  "BJ": { name: "Benin", flag: "🇧🇯" },
  "BM": { name: "Bermuda", flag: "🇧🇲" },
  "BT": { name: "Bhutan", flag: "🇧🇹" },
  "BO": { name: "Bolivien", flag: "🇧🇴" },
  "BA": { name: "Bosnien und Herzegowina", flag: "🇧🇦" },
  "BW": { name: "Botswana", flag: "🇧🇼" },
  "BV": { name: "Bouvetinsel", flag: "🇧🇻" },
  "BR": { name: "Brasilien", flag: "🇧🇷" },
  "IO": { name: "Britisches Territorium im Indischen Ozean", flag: "🇮🇴" },
  "BN": { name: "Brunei", flag: "🇧🇳" },
  "BG": { name: "Bulgarien", flag: "🇧🇬" },
  "BF": { name: "Burkina Faso", flag: "🇧🇫" },
  "BI": { name: "Burundi", flag: "🇧🇮" },
  "KH": { name: "Kambodscha", flag: "🇰🇭" },
  "CM": { name: "Kamerun", flag: "🇨🇲" },
  "CA": { name: "Kanada", flag: "🇨🇦" },
  "CV": { name: "Kap Verde", flag: "🇨🇻" },
  "KY": { name: "Kaimaninseln", flag: "🇰🇾" },
  "CF": { name: "Zentralafrikanische Republik", flag: "🇨🇫" },
  "TD": { name: "Tschad", flag: "🇹🇩" },
  "CL": { name: "Chile", flag: "🇨🇱" },
  "CN": { name: "China", flag: "🇨🇳" },
  "CX": { name: "Weihnachtsinsel", flag: "🇨🇽" },
  "CC": { name: "Kokosinseln", flag: "🇨�" },
  "CO": { name: "Kolumbien", flag: "🇨🇴" },
  "KM": { name: "Komoren", flag: "🇰🇲" },
  "CG": { name: "Kongo", flag: "🇨🇬" },
  "CD": { name: "Kongo (Demokratische Republik)", flag: "🇨🇩" },
  "CK": { name: "Cookinseln", flag: "🇨🇰" },
  "CR": { name: "Costa Rica", flag: "🇨🇷" },
  "CI": { name: "Elfenbeinküste", flag: "🇨🇮" },
  "HR": { name: "Kroatien", flag: "🇭🇷" },
  "CU": { name: "Kuba", flag: "🇨🇺" },
  "CY": { name: "Zypern", flag: "🇨🇾" },
  "CZ": { name: "Tschechien", flag: "🇨🇿" },
  "DK": { name: "Dänemark", flag: "🇩🇰" },
  "DJ": { name: "Dschibuti", flag: "🇩🇯" },
  "DM": { name: "Dominica", flag: "🇩🇲" },
  "DO": { name: "Dominikanische Republik", flag: "🇩🇴" },
  "EC": { name: "Ecuador", flag: "🇪🇨" },
  "EG": { name: "Ägypten", flag: "🇪🇬" },
  "SV": { name: "El Salvador", flag: "🇸🇻" },
  "GQ": { name: "Äquatorialguinea", flag: "🇬🇶" },
  "ER": { name: "Eritrea", flag: "🇪🇷" },
  "EE": { name: "Estland", flag: "🇪🇪" },
  "ET": { name: "Äthiopien", flag: "🇪🇹" },
  "FK": { name: "Falklandinseln", flag: "🇫🇰" },
  "FO": { name: "Färöer", flag: "🇫🇴" },
  "FJ": { name: "Fidschi", flag: "🇫🇯" },
  "FI": { name: "Finnland", flag: "🇫🇮" },
  "FR": { name: "Frankreich", flag: "🇫🇷" },
  "GF": { name: "Französisch-Guayana", flag: "🇬🇫" },
  "PF": { name: "Französisch-Polynesien", flag: "🇵🇫" },
  "TF": { name: "Französische Süd- und Antarktisgebiete", flag: "🇹🇫" },
  "GA": { name: "Gabun", flag: "🇬🇦" },
  "GM": { name: "Gambia", flag: "🇬🇲" },
  "GE": { name: "Georgien", flag: "🇬🇪" },
  "DE": { name: "Deutschland", flag: "🇩🇪" },
  "GH": { name: "Ghana", flag: "🇬🇭" },
  "GI": { name: "Gibraltar", flag: "🇬🇮" },
  "GR": { name: "Griechenland", flag: "🇬🇷" },
  "GL": { name: "Grönland", flag: "🇬🇱" },
  "GD": { name: "Grenada", flag: "🇬🇩" },
  "GP": { name: "Guadeloupe", flag: "🇬🇵" },
  "GU": { name: "Guam", flag: "🇬🇺" },
  "GT": { name: "Guatemala", flag: "🇬🇹" },
  "GG": { name: "Guernsey", flag: "🇬🇬" },
  "GN": { name: "Guinea", flag: "🇬🇳" },
  "GW": { name: "Guinea-Bissau", flag: "🇬🇼" },
  "GY": { name: "Guyana", flag: "🇬🇾" },
  "HT": { name: "Haiti", flag: "🇭🇹" },
  "HM": { name: "Heard und McDonaldinseln", flag: "🇭🇲" },
  "VA": { name: "Vatikanstadt", flag: "🇻🇦" },
  "HN": { name: "Honduras", flag: "🇭🇳" },
  "HK": { name: "Hongkong", flag: "🇭🇰" },
  "HU": { name: "Ungarn", flag: "🇭🇺" },
  "IS": { name: "Island", flag: "🇮🇸" },
  "IN": { name: "Indien", flag: "🇮🇳" },
  "ID": { name: "Indonesien", flag: "🇮🇩" },
  "IR": { name: "Iran", flag: "�🇷" },
  "IQ": { name: "Irak", flag: "🇮🇶" },
  "IE": { name: "Irland", flag: "🇮🇪" },
  "IM": { name: "Isle of Man", flag: "🇮🇲" },
  "IL": { name: "Israel", flag: "🇮🇱" },
  "IT": { name: "Italien", flag: "🇮🇹" },
  "JM": { name: "Jamaika", flag: "🇯🇲" },
  "JP": { name: "Japan", flag: "🇯🇵" },
  "JE": { name: "Jersey", flag: "🇯🇪" },
  "JO": { name: "Jordanien", flag: "🇯🇴" },
  "KZ": { name: "Kasachstan", flag: "🇰🇿" },
  "KE": { name: "Kenia", flag: "🇰🇪" },
  "KI": { name: "Kiribati", flag: "🇰🇮" },
  "KP": { name: "Nordkorea", flag: "🇰�" },
  "KR": { name: "Südkorea", flag: "🇰🇷" },
  "KW": { name: "Kuwait", flag: "🇰🇼" },
  "KG": { name: "Kirgisistan", flag: "🇰🇬" },
  "LA": { name: "Laos", flag: "🇱🇦" },
  "LV": { name: "Lettland", flag: "🇱🇻" },
  "LB": { name: "Libanon", flag: "🇱🇧" },
  "LS": { name: "Lesotho", flag: "🇱🇸" },
  "LR": { name: "Liberia", flag: "🇱🇷" },
  "LY": { name: "Libyen", flag: "🇱🇾" },
  "LI": { name: "Liechtenstein", flag: "🇱🇮" },
  "LT": { name: "Litauen", flag: "🇱🇹" },
  "LU": { name: "Luxemburg", flag: "🇱🇺" },
  "MO": { name: "Macao", flag: "🇲🇴" },
  "MK": { name: "Nordmazedonien", flag: "🇲🇰" },
  "MG": { name: "Madagaskar", flag: "🇲🇬" },
  "MW": { name: "Malawi", flag: "🇲🇼" },
  "MY": { name: "Malaysia", flag: "🇲🇾" },
  "MV": { name: "Malediven", flag: "🇲🇻" },
  "ML": { name: "Mali", flag: "🇲🇱" },
  "MT": { name: "Malta", flag: "🇲🇹" },
  "MH": { name: "Marshallinseln", flag: "🇲🇭" },
  "MQ": { name: "Martinique", flag: "🇲🇶" },
  "MR": { name: "Mauretanien", flag: "🇲🇷" },
  "MU": { name: "Mauritius", flag: "🇲🇺" },
  "YT": { name: "Mayotte", flag: "🇾🇹" },
  "MX": { name: "Mexiko", flag: "🇲🇽" },
  "FM": { name: "Mikronesien", flag: "🇫🇲" },
  "MD": { name: "Moldawien", flag: "🇲🇩" },
  "MC": { name: "Monaco", flag: "🇲🇨" },
  "MN": { name: "Mongolei", flag: "🇲🇳" },
  "ME": { name: "Montenegro", flag: "🇲🇪" },
  "MS": { name: "Montserrat", flag: "🇲🇸" },
  "MA": { name: "Marokko", flag: "🇲🇦" },
  "MZ": { name: "Mosambik", flag: "🇲🇿" },
  "MM": { name: "Myanmar", flag: "🇲🇲" },
  "NA": { name: "Namibia", flag: "🇳🇦" },
  "NR": { name: "Nauru", flag: "🇳🇷" },
  "NP": { name: "Nepal", flag: "🇳🇵" },
  "NL": { name: "Niederlande", flag: "🇳🇱" },
  "NC": { name: "Neukaledonien", flag: "🇳🇨" },
  "NZ": { name: "Neuseeland", flag: "🇳🇿" },
  "NI": { name: "Nicaragua", flag: "🇳🇮" },
  "NE": { name: "Niger", flag: "🇳🇪" },
  "NG": { name: "Nigeria", flag: "🇳🇬" },
  "NU": { name: "Niue", flag: "🇳🇺" },
  "NF": { name: "Norfolkinsel", flag: "🇳🇫" },
  "MP": { name: "Nördliche Marianen", flag: "🇲🇵" },
  "NO": { name: "Norwegen", flag: "🇳🇴" },
  "OM": { name: "Oman", flag: "🇴🇲" },
  "PK": { name: "Pakistan", flag: "🇵🇰" },
  "PW": { name: "Palau", flag: "🇵🇼" },
  "PS": { name: "Palästina", flag: "🇵🇸" },
  "PA": { name: "Panama", flag: "🇵🇦" },
  "PG": { name: "Papua-Neuguinea", flag: "🇵🇬" },
  "PY": { name: "Paraguay", flag: "🇵🇾" },
  "PE": { name: "Peru", flag: "🇵🇪" },
  "PH": { name: "Philippinen", flag: "🇵🇭" },
  "PN": { name: "Pitcairninseln", flag: "🇵🇳" },
  "PL": { name: "Polen", flag: "🇵🇱" },
  "PT": { name: "Portugal", flag: "🇵🇹" },
  "PR": { name: "Puerto Rico", flag: "🇵🇷" },
  "QA": { name: "Katar", flag: "🇶🇦" },
  "RE": { name: "Réunion", flag: "🇷🇪" },
  "RO": { name: "Rumänien", flag: "🇷🇴" },
  "RU": { name: "Russland", flag: "🇷🇺" },
  "RW": { name: "Ruanda", flag: "🇷🇼" },
  "BL": { name: "Saint-Barthélemy", flag: "🇧🇱" },
  "SH": { name: "St. Helena", flag: "🇸🇭" },
  "KN": { name: "St. Kitts und Nevis", flag: "🇰🇳" },
  "LC": { name: "St. Lucia", flag: "🇱🇨" },
  "MF": { name: "Saint-Martin", flag: "🇲🇫" },
  "PM": { name: "Saint-Pierre und Miquelon", flag: "🇵🇲" },
  "VC": { name: "St. Vincent und die Grenadinen", flag: "🇻🇨" },
  "WS": { name: "Samoa", flag: "🇼🇸" },
  "SM": { name: "San Marino", flag: "🇸🇲" },
  "ST": { name: "São Tomé und Príncipe", flag: "🇸🇹" },
  "SA": { name: "Saudi-Arabien", flag: "🇸🇦" },
  "SN": { name: "Senegal", flag: "🇸🇳" },
  "RS": { name: "Serbien", flag: "🇷🇸" },
  "SC": { name: "Seychellen", flag: "🇸🇨" },
  "SL": { name: "Sierra Leone", flag: "🇸🇱" },
  "SG": { name: "Singapur", flag: "🇸🇬" },
  "SX": { name: "Sint Maarten", flag: "🇸🇽" },
  "SK": { name: "Slowakei", flag: "🇸🇰" },
  "SI": { name: "Slowenien", flag: "🇸🇮" },
  "SB": { name: "Salomonen", flag: "🇸🇧" },
  "SO": { name: "Somalia", flag: "🇸🇴" },
  "ZA": { name: "Südafrika", flag: "🇿🇦" },
  "GS": { name: "Südgeorgien und die Südlichen Sandwichinseln", flag: "🇬🇸" },
  "SS": { name: "Südsudan", flag: "🇸🇸" },
  "ES": { name: "Spanien", flag: "🇪🇸" },
  "LK": { name: "Sri Lanka", flag: "🇱🇰" },
  "SD": { name: "Sudan", flag: "🇸🇩" },
  "SR": { name: "Suriname", flag: "🇸🇷" },
  "SJ": { name: "Svalbard und Jan Mayen", flag: "🇸🇯" },
  "SZ": { name: "Swasiland", flag: "🇸🇿" },
  "SE": { name: "Schweden", flag: "🇸🇪" },
  "CH": { name: "Schweiz", flag: "🇨🇭" },
  "SY": { name: "Syrien", flag: "🇸🇾" },
  "TW": { name: "Taiwan", flag: "🇹🇼" },
  "TJ": { name: "Tadschikistan", flag: "🇹🇯" },
  "TZ": { name: "Tansania", flag: "🇹🇿" },
  "TH": { name: "Thailand", flag: "🇹🇭" },
  "TL": { name: "Timor-Leste", flag: "🇹🇱" },
  "TG": { name: "Togo", flag: "🇹🇬" },
  "TK": { name: "Tokelau", flag: "🇹🇰" },
  "TO": { name: "Tonga", flag: "🇹🇴" },
  "TT": { name: "Trinidad und Tobago", flag: "🇹🇹" },
  "TN": { name: "Tunesien", flag: "🇹🇳" },
  "TR": { name: "Türkei", flag: "🇹🇷" },
  "TM": { name: "Turkmenistan", flag: "🇹🇲" },
  "TC": { name: "Turks- und Caicosinseln", flag: "🇹🇨" },
  "TV": { name: "Tuvalu", flag: "🇹🇻" },
  "UG": { name: "Uganda", flag: "🇺🇬" },
  "UA": { name: "Ukraine", flag: "🇺🇦" },
  "AE": { name: "Vereinigte Arabische Emirate", flag: "🇦🇪" },
  "GB": { name: "Großbritannien", flag: "🇬🇧" },
  "US": { name: "USA", flag: "🇺🇸" },
  "UM": { name: "United States Minor Outlying Islands", flag: "🇺🇲" },
  "UY": { name: "Uruguay", flag: "🇺🇾" },
  "UZ": { name: "Usbekistan", flag: "🇺🇿" },
  "VU": { name: "Vanuatu", flag: "🇻🇺" },
  "VE": { name: "Venezuela", flag: "🇻🇪" },
  "VN": { name: "Vietnam", flag: "🇻🇳" },
  "VG": { name: "Britische Jungferninseln", flag: "🇻🇬" },
  "VI": { name: "Amerikanische Jungferninseln", flag: "🇻🇮" },
  "WF": { name: "Wallis und Futuna", flag: "🇼🇫" },
  "EH": { name: "Westsahara", flag: "🇪🇭" },
  "YE": { name: "Jemen", flag: "🇾🇪" },
  "ZM": { name: "Sambia", flag: "🇿🇲" },
  "ZW": { name: "Simbabwe", flag: "🇿🇼" }
};

export default {
  getCountryName(code) {
    return countryData[code]?.name || code;
  },
  getCountryFlag(code) {
    return countryData[code]?.flag || '🏳️';
  },
  getAllCountries() {
    return Object.keys(countryData);
  },
  getCountryData(code) {
    return countryData[code] || { name: code, flag: '🏳️' };
  }
};
